#pragma once

#define INPUT_BUFFER_SIZE 4096
#define INPUT_OVERFLOW_BUFFER_SIZE 256

#define SERVER_BACKLOG 10
#define INPUT_RING_BUFFER_CAPACITY 256
#define PROCESSED_INPUT_LIMIT_PER_UPDATE 256

#define PLAYER_SPAWN_POSITION_X 0
#define PLAYER_SPAWN_POSITION_Y 0

#define LOG_CHUNK_TRANSACTIONS           0
#define LOG_CHUNK_MEMORY_FOOTPRINT       1
