#pragma once

#define DEFAULT_WINDOW_WIDTH 1280
#define DEFAULT_WINDOW_HEIGHT 720

#define VSYNC_ENABLED 1

#define CLIENT_TICK_RATE 64

#define PLAYER_ANIMATION_FPS 10
#define PLAYER_KEYPRESS_RING_BUFFER_CAPACITY 256

#define CAMERA_MOVE_SPEED 10.0f
#define CAMERA_MOVE_BORDER_OFFSET 5
